id: I71F09709
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T02:47:53+00:00'
last_modified: '2022-06-07T18:39:42.354574+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30137
  title: རྒྱུད་བཞི ༼ཟུང་ཅུ་ཟེའི་པར་མ༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    519F:
      image_group_id: I5910
      title: ''
      total_pages: 808
      order: 1
      base_file: 519F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
